### ISSUE TITLE
ApiVersionHeader seems to break integration with Umbraco Heartcore

### ISSUE THREAD

**Issue by NiclasLindqvist** [umbraco/Umbraco.Headless.Client.Net#17]
Since the addition of api-version headers to refit endpoints (see f735d53) the api returns 400 bad request on all requests:

```
{
    "error": {
        "code": "UnsupportedApiVersion",
        "message": "The HTTP resource that matches the request URI 'https://<instance>.s1.umbraco.io/cdn/content/<content-id>' does not support the API version '2.1'."
    }
}
```

Replacing `ApiVersionHeader` value with an empty string `""` gives expected result again.

**Comment by sitereactor** [comment]
Hi @NiclasLindqvist we are aware of the potential issue with this and its something we will get fixed. But as you are getting this it sounds like your project is not on the latest release of Heartcore. Can you email me your project name, so I can double check? `@ morten at umbraco dot com`

**Comment by sitereactor** [comment]
This issue is being addressed in https://github.com/umbraco/Umbraco.Headless.Client.Net/pull/18
