### ISSUE TITLE
Fix CA2007: Do not directly await a Task

### ISSUE THREAD

**Issue by balanikas** [umbraco/Umbraco.Headless.Client.Net#22]
To avoid a deadlock on the UI thread. This can be an issue if this library is meant to be used in Xamarin/UWP applications. 
I have the fix and a configured fxcop analyzer ready in a local branch.
More info here: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007?view=vs-2019

**Comment by sitereactor** [comment]
Hi @balanikas is the fix you want to submit a PR for adding `ConfigureAwait(false);` ? Or is it something else. If you can post an example or simply submit a PR we'd be happy to take a look.

**Comment by balanikas** [comment]
@sitereactor Yes, that is the fix. Plus the inclusion of a package reference to fxcop analyzers. 
Seems I cant create a branch because of insufficient access rights. Can you help me with that?

**Comment by sitereactor** [comment]
I would suggest forking the repository and then create the branch in your local repository. Once you push that to GitHub you can easily make a pull request.
