### ISSUE TITLE
Inconsistent behavior between type delivery endpoints

### ISSUE THREAD

**Issue by miguelcrpinto** [umbraco/Umbraco.Headless.Client.Net#29]
Hi,

I started recently an Umbraco Heartcore project and I'm using the Umbraco.Headless.Client.Net nuget to access the content.

While developing I noticed an inconsistent behavior in the typed methods of the ContentService. I noticed that while GetChildren<T> and GetDescendants<T> **do filter** on contentType, the methods GetById<T> and GetByUrl<T> **do not filter** on contentType.

Is this difference on purpose?

I looked at the implementation of the ContentService here on github and I believe this is not an issue on the library it self but rather on Umbraco headless.

**Comment by sitereactor** [comment]
Hi @miguelcrpinto ContentType filter only exists for methods that can return multiple items and thus make filtering an option.
Both GetById and GetByUrl are used for retrieving a specific single item. For GetById you are explicitly asking for an item with a certain id, so it wouldn't make sent to filter on it. Same for GetByUrl, its a request for a specific single item.
The ContentType is a property on the content item that is returned, so if you don't to treat certain document types differently then you can look for that property.

But maybe you are thinking of a specific scenario or use-case?

**Comment by miguelcrpinto** [comment]
No, I have no particular case in mind but I looked into the implementation and noticed that on the API calls all these methods add the contentType parameter to the query string. This left me wondering if this was the intended behavior or not.
