### ISSUE TITLE
Hotfix for search feature

### ISSUE THREAD

**Issue by netsharpdev** [umbraco/Umbraco.Headless.Client.Net#43]
Hello!
Could you please release fix for search feature, because it currently it is useless?
Fix in commit: d8e96a8c67af9c1e7c4bfdc9c8f8072a91bd0fc8

**Comment by sitereactor** [comment]
yes, sorry, I complete forgot that I needed to tag the commit to kickstart the release.
It's on nuget now: https://www.nuget.org/packages/Umbraco.Headless.Client.Net/1.3.3

**Comment by netsharpdev** [comment]
Thanks! :)
