### ISSUE TITLE
Suggestion: offer a possibility to directly communicate with the Umbraco Backend

### ISSUE THREAD

**Issue by ICATT** [umbraco/Umbraco.Headless.Client.Net#44]
At ICATT, we find we sometimes need to talk to the Umbraco backend endpoints directly, in cases where functionality exists in the backend, but is not implemented in Heartcore yet. For instance, we use this endpoint to properly handle redirects:
`https://{projectAlias}.s1.umbraco.io/umbraco/backoffice/UmbracoApi/RedirectUrlManagement/SearchRedirectUrls`

Do you have a strategy for exposing these kind of functionalities throught the dotnet client? If properly encapsulated, functionalities like this could be offered via the backend at first, and then be rerouted to proper Heartcore endpoints in due time, without breaking clients.

If this aligns with your strategy, we could work on a PR for the SearchRedirectUrls endpoint.

**Comment by sitereactor** [comment]
I would suggest that you create a feature request for what you believe is missing from the APIs. More than happy to looking adding new capabilities, which can support your needs.

Using the Backoffice as per your example is not supported and can change with any future update.

**Comment by sitereactor** [comment]
I'm closing this one as we have just released a Redirect API for Heartcore this week. You can find the documentation here: https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/Redirect/

If you want other endpoints or options for retrieving urls that have been changed and thus would need to be redirected, then please feel free to add a feature request here: https://github.com/umbraco/Umbraco.Heartcore.Issues
