### ISSUE TITLE
Bug in ContentDelivery.cs with filter

### ISSUE THREAD

**Issue by borland-david** [umbraco/Umbraco.Headless.Client.Net#47]
The filter at this location https://github.com/umbraco/Umbraco.Headless.Client.Net/blob/26ae6ab91c8bc291fa7a0a8906e23da28d8e61dc/src/Umbraco.Headless.Client.Net/Delivery/ContentDelivery.cs#L149 uses the variable `page` twice, while I believe the second `page` is meant to be `pageSize`. This means that I can't actually get all my items using the non generic filter.

**Comment by sitereactor** [comment]
This issue was fixed in https://github.com/umbraco/Umbraco.Headless.Client.Net/pull/46 and available from version 1.3.4 of the library on nuget: https://www.nuget.org/packages/Umbraco.Headless.Client.Net/
