### ISSUE TITLE
The GetByTypeAlias method of ContentDelivery is ignoring the contentTypeAlias paramater

### ISSUE THREAD

**Issue by miguelcrpinto** [umbraco/Umbraco.Headless.Client.Net#49]
Hi,

I just found out that the GetByTypeAlias method of ContentDelivery is ignoring the contentTypeAlias paramater. This bug seems to have been introduced in version 1.3 of the nuget package and since then the GetByTypeAlias is obtaining the content type alias from the GetAliasFromClassName method instead of using the method's contentTypeAlias paramater.

I created a [pull request that fixes this issue](https://github.com/umbraco/Umbraco.Headless.Client.Net/pull/48) and I need the nuget to be urgently updated with this fix.

Thanks

**Comment by Zero3** [comment]
Seems like the problem was solved by the referenced pull request, so I will close this issue :).
