### ISSUE TITLE
Impossible to fill a repeatable textstring through API

### ISSUE THREAD

**Issue by raymondvisser1977** [umbraco/Umbraco.Headless.Client.Net#54]
Put
https://api.umbraco.io/content/....id

Request
"uSPs":{
      "$invariant": ["item 1","item 2","item 3","item 4"]
   },

returns:
    "uSPs": {
        "$invariant": []
    },

Along other properties that work perfectly fine.
The model is also being saved btw but it just wont fill the usps property

I tried several formats like :
https://our.umbraco.com/forum/umbraco-heartcore/102738-populate-a-repeatable-textstring-via-headless-client

**Comment by sitereactor** [comment]
I think this was answered through support, but just posting here as we haven't replied here through the tracker (and sorry about that 🙈 ),.

Format of a repeatable string should be 
```
"uSPs":{
"$invariant": [{ "value": "test" }, { "value": "test2" }]
},
```
