### ISSUE TITLE
Image model not matching the Image Media Picker editor output

### ISSUE THREAD

**Issue by gthvidsten** [umbraco/Umbraco.Headless.Client.Net#56]
If you have a document type with an image media picker editor in Heartcore Backoffice this is output like this from the headless API (https://cdn.umbraco.io/content):

```
"myImage": {
          "src": "https://media.umbraco.io/project-id/500hnjka/someImage.jpg",
          "crops": [],
          "media": {
            "_id": "a576b5f8-b440-4436-8dd6-324b5d1c8daf",
            "_url": "https://media.umbraco.io/project-id/500hnjka/someImage.jpg",
            "name": "Some image text",
            "_level": 2,
            "parentId": "3ea46e1e-befa-41e1-85c7-aea2e2d666ab",
            "sortOrder": 0,
            "_createDate": "2023-01-24T09:59:14.697Z",
            "_updateDate": "2023-01-24T09:59:14.697Z",
            "_writerName": null,
            "umbracoFile": {
              "src": "/media/500hnjka/someImage.jpg",
              "crops": [],
              "cropUrls": {},
              "focalPoint": null,
              "focalPointUrlTemplate": "https://media.umbraco.io/project-id/500hnjka/someImage.jpg?width={width}&height={height}&mode=crop&center=0.5,0.5"
            },
            "_creatorName": null,
            "_hasChildren": false,
            "umbracoBytes": 421540,
            "umbracoWidth": 2000,
            "umbracoHeight": 1120,
            "mediaTypeAlias": "Image",
            "umbracoExtension": "jpg"
          },
          "cropUrls": {},
          "focalPointUrlTemplate": "https://media.umbraco.io/project-id/500hnjka/someImage.jpg?width={width}&height={height}&mode=crop&center=0.5,0.5"
        }
```

This data structure does not match the `Umbraco.Headless.Client.Net.Delivery.Models.Image` data model.
It somewhat matches `Umbraco.Headless.Client.Net.Delivery.Models.ImageCropper` but all the data inside the `"media"` property does not get mapped.

So it seems that there is a mapping issue with images.

**Comment by sitereactor** [comment]
Hi @gthvidsten thanks for reporting this. It's most likely related to Image Cropper being introduced as the new default in the Umbraco Backoffice where it was an Upload field before. I have added a task for getting additional models added and clarified in this client library as part of our next sprint. So within long we should be able to push an update.

You are also very welcome to submit a PR if you want. We are always happy to review and merge PRs where possible :)

**Comment by rasmusjp** [comment]
Hi @gthvidsten 

Looking at the output it looks like it's the "new" Media Picker (not the one called legacy) and we currently don't ship with a model for it. However you should be able to create a model for it that looks something like this:

```csharp
public class MediaPicker : ImageCropper
{
    public Media Media { get; set; }
}
```

The model for `ImageCropper` is ment to be used with the `Image Cropper` property editor. `Image` is a representation of the `Image` media type, it inherits from `Media` and when deserialising any media that has the document type `Image` is automatically deserialised to the `Image` model.

**Comment by sitereactor** [comment]
A model has now been added to the client library to make it easier to work with.
The following PR has the details: https://github.com/umbraco/Umbraco.Headless.Client.Net/pull/58

Version 1.4.1 is now available on nuget: https://www.nuget.org/packages/Umbraco.Headless.Client.Net/1.4.1
